spring:
    datasource:
        url: jdbc:mysql://120.53.103.222:3306/cloudDemo
        username: root
        password: Mysql123.
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8077

management:
    endpoint:
        health:
            show-details: always # 显示健康状态详情
    endpoints:
        web:
            exposure:
                include: "*" # 暴露所有端点
            base-path: /actuator